name: version auto-incrementing & package publishing
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: ["master"]

jobs:
  build:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    
    runs-on: ubuntu-latest

    steps:
      - name: Checking out v3
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m
          pip install wheel pyyaml sortedcontainers requests semver

      - name: Increment version
        run: python ./.github/workflows/version.py --increment

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "increment to v$(python ./.github/workflows/version.py --get)"
          git push --force
