name: Tests
on:
  pull_request:

jobs:
  coverage_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out v3
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install sortedcontainers numpy coverage

      - name: Run tests
        run: |
          coverage run test/test.py
          coverage report -m sigfig/sigfig.py
